import React from 'react'
import { Link } from 'react-router-dom'

type TermsSection = {
  id: string
  title: string
  body: React.ReactNode
}

const sections: TermsSection[] = [
  {
    id: 'about',
    title: '1. About These Terms',
    body: (
      <>
        <p>
          These Terms and Conditions govern the use of Kari Time, a software service
          provided for hospitality venues to record staff shifts and prepare payroll
          information.
        </p>
        <p>
          This is a practical draft for a small SaaS business and is not legal advice.
          If you need legal advice for your venue or business, you should speak to a
          qualified solicitor.
        </p>
      </>
    ),
  },
  {
    id: 'service',
    title: '2. Service Description',
    body: (
      <>
        <p>Kari Time is a hospitality shift-tracking SaaS platform. It may include features such as:</p>
        <ul>
          <li>staff clock in and clock out records;</li>
          <li>timesheets and shift summaries;</li>
          <li>manager review and corrections;</li>
          <li>pay rate support and worked-hours calculations; and</li>
          <li>payroll export files and reports for venues.</li>
        </ul>
        <p>
          Kari Time helps organise and export payroll-related information, but it does
          not replace your responsibility to review payroll, employment status, pay,
          breaks, holiday, tax, pension, and other legal obligations.
        </p>
      </>
    ),
  },
  {
    id: 'accounts',
    title: '3. Accounts and Access',
    body: (
      <>
        <p>
          You are responsible for keeping account credentials secure and for all
          activity carried out using your account. You must ensure that user access is
          limited to authorised staff and managers only.
        </p>
        <p>
          You must promptly remove access for team members who no longer need to use
          the service.
        </p>
      </>
    ),
  },
  {
    id: 'acceptable-use',
    title: '4. Acceptable Use',
    body: (
      <>
        <p>You agree not to misuse Kari Time. In particular, you must not:</p>
        <ul>
          <li>use the service for unlawful, fraudulent, or harmful purposes;</li>
          <li>attempt to access accounts, data, or systems without permission;</li>
          <li>interfere with the service, security, or availability of the platform;</li>
          <li>upload malicious code, scripts, or content; or</li>
          <li>use the service in a way that breaches applicable employment or data protection law.</li>
        </ul>
        <p>
          You are responsible for ensuring shift entries, break deductions, pay rates,
          and payroll inputs entered by your team are accurate and reviewed before use.
        </p>
      </>
    ),
  },
  {
    id: 'employment-law',
    title: '5. Compliance With Employment Law',
    body: (
      <>
        <p>
          Kari Time is a record-keeping and export tool. You remain responsible for
          complying with all applicable employment, payroll, tax, working time, minimum
          wage, and record-keeping requirements.
        </p>
        <p>
          Any calculations or reports generated by Kari Time should be checked by a
          manager before payroll is processed.
        </p>
      </>
    ),
  },
  {
    id: 'data-handling',
    title: '6. Data Handling',
    body: (
      <>
        <p>
          Kari Time processes information needed to provide the service, including
          account details, staff names or identifiers, shift times, worked hours,
          timesheet records, and payroll export data entered by users.
        </p>
        <p>We use this information to:</p>
        <ul>
          <li>operate and secure the service;</li>
          <li>store and display shift and timesheet records;</li>
          <li>generate exports and reports requested by users;</li>
          <li>maintain backups, logs, and basic service diagnostics; and</li>
          <li>understand website usage via analytics (e.g. Google Analytics). See our Privacy Policy for details.</li>
        </ul>
        <p>
          We will take reasonable technical and organisational steps to protect data in
          our systems. You are responsible for the lawfulness of the data you enter and
          for meeting your obligations to staff under applicable data protection law,
          including UK GDPR and the Data Protection Act 2018 where applicable.
        </p>
      </>
    ),
  },
  {
    id: 'availability',
    title: '7. Availability and Changes',
    body: (
      <>
        <p>
          We may update, improve, or change features from time to time. We will use
          reasonable efforts to keep Kari Time available, but we do not guarantee that
          the service will be uninterrupted or error-free at all times.
        </p>
        <p>
          Temporary downtime may occur for maintenance, updates, or issues outside our
          reasonable control.
        </p>
      </>
    ),
  },
  {
    id: 'liability',
    title: '8. Liability',
    body: (
      <>
        <p>
          Kari Time is provided on an &quot;as is&quot; and &quot;as available&quot;
          basis. To the fullest extent permitted by law, we exclude implied warranties
          that are not expressly stated in these terms.
        </p>
        <p>
          We are not liable for payroll errors, underpayments, overpayments, missed
          payments, tax issues, or employment disputes arising from inaccurate or
          incomplete data entered by users, incorrect configuration, or failure to
          review reports before payroll processing.
        </p>
        <p>
          Nothing in these terms excludes or limits liability for fraud, fraudulent
          misrepresentation, death, or personal injury caused by negligence, or any
          other liability that cannot be excluded under law.
        </p>
      </>
    ),
  },
  {
    id: 'termination',
    title: '9. Suspension and Termination',
    body: (
      <>
        <p>
          You may stop using Kari Time and request account closure at any time. We may
          suspend or terminate access if you breach these terms, misuse the service, or
          where reasonably necessary to protect the platform or other users.
        </p>
        <p>
          On termination, access to the service may be removed. You should export any
          records you need before closing your account.
        </p>
      </>
    ),
  },
  {
    id: 'general',
    title: '10. General',
    body: (
      <>
        <p>
          If any part of these terms is found unenforceable, the remaining parts will
          continue to apply. Our failure to enforce a right immediately does not waive
          that right.
        </p>
      </>
    ),
  },
  {
    id: 'law',
    title: '11. Governing Law and Jurisdiction',
    body: (
      <>
        <p>
          These terms are governed by the laws of England and Wales. The courts of
          England and Wales will have exclusive jurisdiction over disputes relating to
          these terms or the use of Kari Time, unless applicable law requires
          otherwise.
        </p>
      </>
    ),
  },
]

export function TermsPage() {
  return (
    <div
      className="terms-page"
      style={{
        minHeight: '100vh',
        background:
          'radial-gradient(circle at top right, rgba(200,133,58,0.16), transparent 46%), #12100e',
        color: '#f5f0e8',
        padding: '2rem 1rem 3rem',
      }}
    >
      <style>
        {`
          .terms-page .terms-prose p { margin: 0 0 0.8rem; }
          .terms-page .terms-prose p:last-child { margin-bottom: 0; }
          .terms-page .terms-prose ul {
            margin: 0 0 0.8rem;
            padding-left: 1.15rem;
            list-style: disc;
          }
          .terms-page .terms-prose li {
            margin: 0 0 0.35rem;
            color: rgba(245,240,232,0.78);
          }
          .terms-page .terms-prose li:last-child { margin-bottom: 0; }
        `}
      </style>
      <div
        style={{
          maxWidth: 860,
          margin: '0 auto',
          border: '1px solid rgba(200,133,58,0.22)',
          background: 'rgba(18,16,14,0.88)',
          boxShadow: '0 16px 40px rgba(0,0,0,0.28)',
          borderRadius: 14,
          overflow: 'hidden',
        }}
      >
        <header
          style={{
            padding: '1.5rem 1.25rem',
            borderBottom: '1px solid rgba(200,133,58,0.18)',
            background: 'linear-gradient(180deg, rgba(200,133,58,0.08), rgba(18,16,14,0))',
          }}
        >
          <p
            style={{
              margin: 0,
              color: '#e8a855',
              fontSize: '0.76rem',
              letterSpacing: '0.12em',
              textTransform: 'uppercase',
              fontWeight: 700,
            }}
          >
            Kari Time
          </p>
          <h1
            style={{
              margin: '0.45rem 0 0',
              fontFamily: '"Playfair Display", Georgia, serif',
              fontSize: 'clamp(1.8rem, 4vw, 2.4rem)',
              lineHeight: 1.15,
              color: '#f5f0e8',
            }}
          >
            Terms and Conditions
          </h1>
          <p style={{ margin: '0.75rem 0 0', color: 'rgba(245,240,232,0.72)' }}>
            Effective date: 24 February 2026
          </p>
          <p style={{ margin: '0.4rem 0 0', color: 'rgba(245,240,232,0.58)' }}>
            Draft terms for a UK hospitality shift-tracking SaaS. Not legal advice.
          </p>
          <p style={{ margin: '0.9rem 0 0', display: 'flex', gap: '0.8rem', flexWrap: 'wrap' }}>
            <Link to="/" style={linkStyle}>
              Back to home
            </Link>
            <Link to="/login" style={linkStyleMuted}>
              Go to login
            </Link>
          </p>
        </header>

        <main style={{ padding: '1.25rem' }}>
          <section
            style={{
              padding: '0.95rem 1rem',
              border: '1px solid rgba(200,133,58,0.16)',
              borderRadius: 10,
              background: 'rgba(200,133,58,0.05)',
              color: 'rgba(245,240,232,0.78)',
              lineHeight: 1.55,
            }}
          >
            <p style={{ margin: 0 }}>
              By using Kari Time, you agree to these terms. If you are using Kari Time on behalf
              of a venue or business, you confirm that you have authority to accept these terms for
              that organisation.
            </p>
          </section>

          <div style={{ marginTop: '1rem' }}>
            {sections.map((section) => (
              <section
                key={section.id}
                aria-labelledby={section.id}
                style={{
                  padding: '1rem',
                  borderBottom: '1px solid rgba(200,133,58,0.12)',
                }}
              >
                <h2
                  id={section.id}
                  style={{
                    margin: '0 0 0.7rem',
                    fontFamily: '"Playfair Display", Georgia, serif',
                    fontSize: '1.3rem',
                    lineHeight: 1.2,
                    color: '#f5f0e8',
                  }}
                >
                  {section.title}
                </h2>
                <div className="terms-prose" style={proseStyle}>
                  {section.body}
                </div>
              </section>
            ))}
          </div>
        </main>
      </div>
    </div>
  )
}

const linkStyle: React.CSSProperties = {
  color: '#12100e',
  background: '#c8853a',
  border: '1px solid #c8853a',
  borderRadius: 6,
  padding: '0.55rem 0.85rem',
  textDecoration: 'none',
  fontWeight: 700,
  fontSize: '0.95rem',
}

const linkStyleMuted: React.CSSProperties = {
  color: '#f5f0e8',
  background: 'transparent',
  border: '1px solid rgba(245,240,232,0.22)',
  borderRadius: 6,
  padding: '0.55rem 0.85rem',
  textDecoration: 'none',
  fontWeight: 600,
  fontSize: '0.95rem',
}

const proseStyle: React.CSSProperties = {
  color: 'rgba(245,240,232,0.78)',
  lineHeight: 1.65,
}
